//! Generated protobuf modules
//! 
//! This module re-exports the generated protobuf code.
//! The actual files are generated by tonic-build in build.rs.

// These modules will be generated by build.rs
// For now, we provide placeholder modules
